CREATE OR REPLACE VIEW all_players AS(
    SELECT
    GAMEID,
    T1P1_SUMMONERID,
    T1P1_SUMMONERNAME,
    'team1' AS TEAM,
    T1P1_LP,
    T1P1_KILLS,    
    T1P1_ASSISTS,
    T1P1_DEATHS,
    T1P1_GOLDEARNED,
    T1P1_TOTALDAMAGEDEALTTOCHAMPIONS,
    T1P1_BAN_CHAMPID,
    T1P1_CHAMPID,
    AVERAGE_LP,
    T1P1_ROLE,
    T1_TEAMID,
    T1_WIN,
    GAMECREATION
    FROM matches
    UNION ALL
    SELECT
    GAMEID,
    T1P2_SUMMONERID,
    T1P2_SUMMONERNAME,
    'team1' AS TEAM,
    T1P2_LP,
    T1P2_KILLS,    
    T1P2_ASSISTS,
    T1P2_DEATHS,
    T1P2_GOLDEARNED,
    T1P2_TOTALDAMAGEDEALTTOCHAMPIONS,
    T1P2_BAN_CHAMPID,
    T1P2_CHAMPID,
    AVERAGE_LP,
    T1P2_ROLE,
    T1_TEAMID,
    T1_WIN,
    GAMECREATION
    FROM matches
    UNION ALL 
    SELECT
    GAMEID,
    T1P3_SUMMONERID,
    T1P3_SUMMONERNAME,
    'team1' AS TEAM,
    T1P3_LP,
    T1P3_KILLS,    
    T1P3_ASSISTS,
    T1P3_DEATHS,
    T1P3_GOLDEARNED,
    T1P3_TOTALDAMAGEDEALTTOCHAMPIONS,
    T1P3_BAN_CHAMPID,
    T1P3_CHAMPID,
    AVERAGE_LP,
    T1P3_ROLE,
    T1_TEAMID,
    T1_WIN,
    GAMECREATION
    FROM matches
    UNION ALL 
    SELECT
    GAMEID,
    T1P4_SUMMONERID,
    T1P4_SUMMONERNAME,
    'team1' AS TEAM,
    T1P4_LP,
    T1P4_KILLS,    
    T1P4_ASSISTS,
    T1P4_DEATHS,
    T1P4_GOLDEARNED,
    T1P4_TOTALDAMAGEDEALTTOCHAMPIONS,
    T1P4_BAN_CHAMPID,
    T1P4_CHAMPID,
    AVERAGE_LP,
    T1P4_ROLE,
    T1_TEAMID,
    T1_WIN,
    GAMECREATION
    FROM matches
    UNION ALL 
    SELECT
    GAMEID,
    T1P5_SUMMONERID,
    T1P5_SUMMONERNAME,
    'team1' AS TEAM,
    T1P5_LP,
    T1P5_KILLS,    
    T1P5_ASSISTS,
    T1P5_DEATHS,
    T1P5_GOLDEARNED,
    T1P5_TOTALDAMAGEDEALTTOCHAMPIONS,
    T1P5_BAN_CHAMPID,
    T1P5_CHAMPID,
    AVERAGE_LP,
    T1P5_ROLE,
    T1_TEAMID,
    T1_WIN,
    GAMECREATION
    FROM matches
    UNION ALL 
    SELECT
    GAMEID,
    T2P1_SUMMONERID,
    T2P1_SUMMONERNAME,
    'team2' AS TEAM,
    T2P1_LP,
    T2P1_KILLS,    
    T2P1_ASSISTS,
    T2P1_DEATHS,
    T2P1_GOLDEARNED,
    T2P1_TOTALDAMAGEDEALTTOCHAMPIONS,
    T2P1_BAN_CHAMPID,
    T2P1_CHAMPID,
    AVERAGE_LP,
    T2P1_ROLE,
    '0' AS T2_TEAMID,
    T1_WIN,
    GAMECREATION
    FROM matches
    UNION ALL
    SELECT
    GAMEID,
    T2P2_SUMMONERID,
    T2P2_SUMMONERNAME,
    'team2' AS TEAM,
    T2P2_LP,
    T2P2_KILLS,    
    T2P2_ASSISTS,
    T2P2_DEATHS,
    T2P2_GOLDEARNED,
    T2P2_TOTALDAMAGEDEALTTOCHAMPIONS,
    T2P2_BAN_CHAMPID,
    T2P2_CHAMPID,
    AVERAGE_LP,
    T2P2_ROLE,
    '0' AS T2_TEAMID,
    T1_WIN,
    GAMECREATION
    FROM matches
    UNION ALL 
    SELECT
    GAMEID,
    T2P3_SUMMONERID,
    T2P3_SUMMONERNAME,
    'team2' AS TEAM,
    T2P3_LP,
    T2P3_KILLS,    
    T2P3_ASSISTS,
    T2P3_DEATHS,
    T2P3_GOLDEARNED,
    T2P3_TOTALDAMAGEDEALTTOCHAMPIONS,
    T2P3_BAN_CHAMPID,
    T2P3_CHAMPID,
    AVERAGE_LP,
    T2P3_ROLE,
    '0' AS T2_TEAMID,
    T1_WIN,
    GAMECREATION
    FROM matches
    UNION ALL 
    SELECT
    GAMEID,
    T2P4_SUMMONERID,
    T2P4_SUMMONERNAME,
    'team2' AS TEAM,
    T2P4_LP,
    T2P4_KILLS,    
    T2P4_ASSISTS,
    T2P4_DEATHS,
    T2P4_GOLDEARNED,
    T2P4_TOTALDAMAGEDEALTTOCHAMPIONS,
    T2P4_BAN_CHAMPID,
    T2P4_CHAMPID,
    AVERAGE_LP,
    T2P4_ROLE,
    '0' AS T2_TEAMID,
    T1_WIN,
    GAMECREATION
    FROM matches
    UNION ALL 
    SELECT
    GAMEID,
    T2P5_SUMMONERID,
    T2P5_SUMMONERNAME,
    'team2' AS TEAM,
    T2P5_LP,
    T2P5_KILLS,    
    T2P5_ASSISTS,
    T2P5_DEATHS,
    T2P5_GOLDEARNED,
    T2P5_TOTALDAMAGEDEALTTOCHAMPIONS,
    T2P5_BAN_CHAMPID,
    T2P5_CHAMPID,
    AVERAGE_LP,
    T2P5_ROLE,
    '0' AS T2_TEAMID,
    T1_WIN,
    GAMECREATION
    FROM matches
)